### ISSUE TITLE
Heavy (Hard) Vulcan materia slost number in Reunion

### ISSUE THREAD

**Issue by 4aiman** [Shojy/Tseng#8]
I'm playing FF7 (Steam) with the Reunion mod and have noticed that Barret's Heavy (Hard) Vulcan weapon has 4 slots (linked) instead of just two.
So, I googled a bit and found that various sources have different opinions on that matter.
I'm not sure whether it's Reunion's fault or Steam version is different in that regard, but yeah :)

**Comment by Shojy** [comment]
Thanks. It can vary between mods, and the data packs in use weren't the best option for loading this data.  As of v0.10-alpha, this data is now read from the game files directly, and v0.11-alpha fixes mod support for naming.

v0.11-alpha onwards should correctly work with Reunion, New Threat, and other mods that may change equipment or materia details
